#!/usr/bin/env python3
"""Rasterises the app's typefaces into ui/font_data.c.

The console build has no font library, so glyphs are drawn from antialiased
8-bit coverage bitmaps generated here, once, from Liberation Sans (SIL Open
Font License 1.1). Only printable ASCII is included; anything else is drawn as
'?'. Re-run after changing sizes:

    python3 tools/genfont.py > ui/font_data.c
"""
import sys
from PIL import Image, ImageDraw, ImageFont

REG = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
BOLD = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"
# (C name, file, pixel size)
FONTS = [
    ("small", REG, 22),
    ("body", REG, 28),
    ("strong", BOLD, 28),
    ("title", BOLD, 44),
]
FIRST, LAST = 32, 126


def render(font, ch):
    pad = font.size
    img = Image.new("L", (pad * 3, pad * 3), 0)
    base = pad * 2
    ImageDraw.Draw(img).text((pad, base), ch, font=font, fill=255, anchor="ls")
    box = img.getbbox()
    adv16 = round(font.getlength(ch) * 16)
    if box is None:
        return None, 0, 0, 0, 0, adv16
    l, t, r, b = box
    crop = img.crop(box)
    return crop.tobytes(), r - l, b - t, l - pad, base - t, adv16


out = []
w = out.append
w("/* Generated by tools/genfont.py from Liberation Sans (SIL OFL 1.1). Do not edit. */")
w('#include "gfx.h"\n')
for name, path, px in FONTS:
    f = ImageFont.truetype(path, px)
    asc, desc = f.getmetrics()
    blob = bytearray()
    rows = []
    for c in range(FIRST, LAST + 1):
        data, gw, gh, bx, by, adv = render(f, chr(c))
        off = len(blob)
        if data:
            blob += data
        rows.append((off, gw, gh, bx, by, adv))
    w(f"static const uint8_t bits_{name}[] = {{")
    for i in range(0, len(blob), 24):
        w("    " + ",".join(str(x) for x in blob[i:i + 24]) + ",")
    if not blob:
        w("    0")
    w("};")
    w(f"static const gfx_glyph glyphs_{name}[] = {{")
    for off, gw, gh, bx, by, adv in rows:
        w(f"    {{{off},{gw},{gh},{bx},{by},{adv}}},")
    w("};")
    w(f"const gfx_font font_{name} = {{{px}, {asc}, {asc + desc}, glyphs_{name}, bits_{name}}};\n")
sys.stdout.write("\n".join(out) + "\n")
